version: "3.6"

services:
  vaga-creche-db:
    image: postgres:12
    container_name: vaga-creche-db
    restart: unless-stopped
    volumes:
      - /srv/db_vaga:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - vaga-creche-db-nw
    ports:
      - "5432:5432"

  vaga-creche-djangoapp:
    build: SME-VagasNaCreche-API/
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - ./SME-VagasNaCreche-API/:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    env_file:
      - .env
    networks:
      - vaga-creche-db-nw
      - vaga-creche-web_nw
    depends_on:
      - vaga-creche-db
      - vaga-creche-redis

  vaga-creche-nginx:
    image: nginx:1.15-alpine
    container_name: vaga-creche-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - vaga-creche-web_nw
    depends_on:
      - vaga-creche-djangoapp
      - vaga-creche-db
    ports:
      - "80:80"

  vaga-creche-redis:
    image: redis:3.2-alpine
    container_name: vaga-creche-redis
    volumes:
      - redis_data:/data
    networks:
      - vaga-creche-db-nw

networks:
  vaga-creche-db-nw:
    driver: bridge
  vaga-creche-web_nw:
    driver: bridge

volumes:
  db_data:
  static:
  media:
  redis_data: