# Generated by Django 2.2.6 on 2019-11-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBuscaEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitute', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cd_serie', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'pesq_historico_busca_endereco',
            },
        ),
    ]
